version: '3.8'

services:
  app:
    build: .
    container_name: async_processor_app
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DB_NAME=database_name
    command: ["python", "async_dataframe_processing.py"]

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
